# Generated by Django 6.0.1 on 2026-04-25 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description_name', models.CharField(blank=True, max_length=255)),
                ('resume_name', models.CharField(max_length=255)),
                ('overview_score', models.FloatField(default=0.0)),
                ('responsibilities_score', models.FloatField(default=0.0)),
                ('qualifications_score', models.FloatField(default=0.0)),
                ('skills_score', models.FloatField(default=0.0)),
                ('overall_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-overall_score', '-created_at'],
            },
        ),
    ]
