# Generated by Django 6.0.1 on 2026-04-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='extra_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidate',
            name='extracted_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidate',
            name='matched_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidate',
            name='missing_skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
