# Generated by Django 6.0.4 on 2026-05-02 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_candidate_extra_skills_candidate_extracted_skills_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
